[tasks.format]
command = "cargo"
args = ["fmt"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.compile]
command = "cargo"
args = ["build", "-r"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.default]
dependencies = [
    "format",
    "compile",
    "test"
]