name: Rust

on:
#   push:
#     branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  create-env:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Configure AWS SSM credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::095213111338:role/GithubOIDCReadSSM
        aws-region: ap-southeast-1
    - name: Create .env
      run: aws ssm get-parameters --name="$SSM_NAME" --query Parameters[0].Value | xargs printf > .env
      env:
        SSM_NAME: ${{ secrets.SSM_NAME }}
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Format
      run: cargo fmt
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
  deploy:
    runs-on: ubuntu-latest
